image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_BASEURL: https://test.ipspace.net

pages:
  script:
  - hugo version
  - hugo
  artifacts:
    paths:
    - public
  only:
  - publish
