image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_BASEURL: https://ipspace.gitlab.io/blog/

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
