baseURL: https://blog.ipspace.net/
languageCode: en-us
title: ipSpace.net blog
theme: ipspace
summarylength: 3000
uglyurls: true

permalinks:
  posts: "/:year/:month/:filename"
  archm: "/:year/:month/index"
  archy: "/:year/index"
  tags: "/tag/:title"

taxonomies:
  tag: tags

params:
  notags: [ Workshop, Podcast, Training, Software Gone Wild, 
    "You've asked for it", "Gestalt IT", marketing, Subscription, Video ]
