# Updated on 2021-02-27 with --tags BGP
---
category: [ BGP ]
title: BGP Resources
sidebar:
- HTML_Subscription
- toc
- HTML_Products
- HTML_About

blog:
  type: links
  links:
  - https://blog.ipspace.net/2021/05/routing-unnumbered-interfaces.html
  - https://blog.ipspace.net/2021/05/segment-routing-mpls-bgp-free-core.html
  - https://blog.ipspace.net/2021/06/interactions-ospf-bgp.html
  - https://blog.ipspace.net/2021/01/bgp-rpki-aws.html
  - https://blog.ipspace.net/2021/01/bgp-igp-metric-admin-distance.html
  - https://blog.ipspace.net/2021/06/ucmp-bgp-link-bandwidth.html
  - https://blog.ipspace.net/2021/06/ospf-bgp-ls.html
  - https://blog.ipspace.net/2020/11/pluginized-protocols.html
  - https://blog.ipspace.net/2020/10/redistributing-bgp-into-ospf.html
  - https://blog.ipspace.net/2020/04/can-we-trust-bgp-next-hops-part-1.html
  - https://blog.ipspace.net/2020/04/can-we-trust-bgp-next-hops-part-2.html
  - https://blog.ipspace.net/2020/04/next-hop-vtep-reachability-evpn.html
  - https://blog.ipspace.net/2019/01/bgp-as-high-availability-protocol.html
  - https://blog.ipspace.net/2019/11/using-bgp-for-firewall-high.html
  - https://blog.ipspace.net/2019/12/tuning-bgp-convergence-in-high.html
  - https://blog.ipspace.net/2019/07/rant-some-internet-service-providers.html
  - https://blog.ipspace.net/2019/10/redundant-bgp-connectivity-on-single.html
  
podcasts:
  type: links
  links:
  - https://blog.ipspace.net/2021/01/freertr-deep-dive.html
  - https://blog.ipspace.net/2020/06/bgp-navel-gazing.html
  - https://blog.ipspace.net/2020/08/trusting-routing-protocols.html
  - https://blog.ipspace.net/2020/02/podcast-bgp-in-public-cloud-revisited.html
  - https://blog.ipspace.net/2019/10/openbgpd-with-claudio-jeker-on-software.html

bottom: |
  <p style="padding: 1em 2em;
    border-top: 1px solid;
    border-bottom: 1px solid;
    font-size: 90%;
    margin-top: 3em;">
  This article written by Ivan Pepelnjak in early 2000s was originally published on
  CT3 wiki which became unreachable in 2019.
  The text was retrieved from an Internet Archive snapshot, updated, and republished
  on ipSpace.net in late 2020.
  </p>
