---
category: [ OSPF ]
title: OSPF Resources
sidebar:
- HTML_Subscription
- toc
- HTML_Products
- HTML_About

blog:
  type: links
  links:
  - https://blog.ipspace.net/2016/10/ansible-versus-puppet-in-initial-device.html
  - https://blog.ipspace.net/2018/03/how-do-you-get-information-from-network.html
  - https://blog.ipspace.net/2017/08/upgrade-network-device-software-with.html
  - https://blog.ipspace.net/2019/01/not-so-fast-ansible-cisco-ios-cant-keep.html
  - https://blog.ipspace.net/2017/09/collect-ssh-keys-with-ansible.html
  - https://blog.ipspace.net/2018/04/avoid-write-only-code.html
  - https://blog.ipspace.net/2017/02/navigating-complex-data-structures-in.html
  - https://blog.ipspace.net/2016/12/push-configuration-snippet-to-bunch-of.html
  - https://blog.ipspace.net/2016/12/generating-ospf-bgp-and-mplsvpn.html

bottom: |
  <p style="padding: 1em 2em;
    border-top: 1px solid;
    border-bottom: 1px solid;
    font-size: 90%;
    margin-top: 3em;">
  This article written by Ivan Pepelnjak in early 2000s was originally published on
  CT3 wiki which became unreachable in 2019.
  The text was retrieved from an Internet Archive snapshot and republished on ipSpace.net
  in late 2020.
  </p>
