comments:
- date: 06 September 2016 13:59
  html: About Netconf and Cisco Nexus, there may be some light at the end of the tunnel,
    because Cisco exposes the XSD schema to write XML configuration ... but ...<br
    /><br />Netconf tools use Yang (and not XSD) to model data.<br /><br />So here
    is a question I asked on the forum of OpenDaylight (with southbond in netconf)
    ... No response ... yet<br /><br />https://ask.opendaylight.org/question/12986/how-to-convert-xsd-to-yang-model/
  id: '6036597689429043806'
  image: https://lh4.googleusercontent.com/-g01JrfrptSE/AAAAAAAAAAI/AAAAAAAAALA/WYrWErci_XA/s32-c/photo.jpg
  name: Mathieu Millet
  profile: https://www.blogger.com/profile/01604817518401015592
  pub: '2016-09-06T13:59:59.140+02:00'
  ref: '424382852406378820'
  type: comment
count: 1
id: '424382852406378820'
type: post
url: 2016/09/questions-about-network-automation.html
