---
category: [ Automation,Ansible ]
title: Yet Another Network Automation Journey
sort_field: name
upcoming_articles: true

sidebar:
- HTML_Subscription
- toc
- HTML_Products
- HTML_About

bottom: |
  <hr /><em>This article is an account of how to get started with network automation, and some common use cases.
  You can reach Anne via [LinkedIn](https://www.linkedin.com/in/abaretta).</em>
  <hr />

  {{ next }}

intro: |
  <hr />This article was written by [Anne Baretta](https://www.linkedin.com/in/abaretta),
  network architect at [Falco Networks](https://www.falco-networks.com).<hr />

# upcoming:
# - NAT and Multiple Interfaces
# - iBGP Solutions
