---
category: [ BGP,Design ]
title: BGP as High Availability Protocol
sort_field: name

sidebar:
- HTML_Subscription
- toc
- HTML_Products
- HTML_About

bottom: |
  <hr /><em>This article is a summary of ideas Nicola used in
  multiple network designs. You can reach Nicola through [his web site](http://modena.to/) and
  engage him directly or through [ExpertExpress service](https://www.ipspace.net/ExpertExpress).</em>
  <hr />

  {{ next }}

intro: |
  <hr />This article was written by [Nicola Modena](https://www.linkedin.com/in/nmodena/),
  independent network and security architect, and a member of ipSpace.net
  [ExpertExpress team](https://www.ipspace.net/ExpertExpress).<hr />

upcoming:
- NAT and Multiple Interfaces
- iBGP Solutions

